---
title: "Laboratório 1.1"
author: "Lucas Cunha Alvarenga & Marcos Cavalcanti"
date: "07/04/2022"
output: word_document
---
  
## Exercício 1

  
De acordo com a ortodoxia da Microeconomia, o objetivo de qualquer agente racional é otimizar a utilidade das suas ações. Neste caso, definiremos o funcional de utilidade igual a função de Lucro combinado dos projetos. Segue as definições abaixo.  

Seja o vetor de decisões de investimento, $D = [d_1,d_2,d_3,d_4,d_5] \in \{0,1\}^{5} \subset \mathbb{R}^{5}$
$$d_i = \begin{cases} 1,& \mbox{se há investimento no projeto}\; i  \\ 0, & \mbox{se não há investimento no projeto}\; i\end{cases}$$
  
o vetor de investimentos, $C = [c_1,c_2,c_3,c_4,c_5] \in \mathbb{R}^{5}$,
$$\;c_i = (Investimento)_i,$$
  
o vetor de valor presente e $VP = [vp_1,vp_2,vp_3,vp_4,vp_5] \in \mathbb{R}^{5}$,
$$vp_i = (Valor Presente)_i $$

Desse modo, definimos o produto escalar tal que sejam $X,Y$ vetores, $X = [x_1,x_2,...,x_k]$ e $y = [y_1,y_2,...,y_k]$ ,então, 
$$X \cdot Y = (x_1y_1+x_2y_2 \;+\; ... +\; x_ky_k) \in \mathbb{R} $$
  
E temos a função de valor presente líquido (VPL) dada por 
$$VPL(VP,I,D) \;= \;[(VP-I) \cdot D]\;\in \mathbb{R}$$
  
Por fim, nosso problema é
$$\max\limits_{d_i \in D} \; U(VP,I,D) \;= \;VPL(VP,I,D)\;,\;s.a. \;I \cdot D \leq 600$$
  
#### Resultados

$$VPL^{*} = USD\; 400 \;mil$$

$$D = [1,1,0,0,1]$$

Ou seja, o conjunto ideal de projetos é o Projeto 1, Projeto 2 e Projeto 5.  

  
  
## Exercício 2
  
### PARTE I  
Similarmente a Questão 1, nosso objetivo é otimizar a utilidade do agente tomador de decisão. Contudo, agora estamos lidando com um cenário com mais opções e mais restrições.

Seja $D_X$ o vetor de decisão de investimento na avenida entre Augen e Burger, $C_X$ seu vetor de custos e $VPL_X$ seu vetor de VPL. Então, 
$$D_X = [dx_1,dx_2,dx_3,dx_4] \in \{0,1\}^{4} \subset \mathbb{R}^{4}$$
$$C_X = [cx_1,cx_2,cx_3,cx_4] \in \mathbb{R}^{4}$$
$$VPL_X = [vplx_1,vplx_2,vplx_3,vplx_4] \in \mathbb{R}^{4}$$

Seja $D_Y$ o vetor de decisão de investimento na Ponte na Cay Road, $C_Y$ seu vetor de custos e $VPL_Y$ seu vetor de VPL. Então, 
$$D_Y = [dy_1,dy_2,dy_3] \in \{0,1\}^{3} \subset \mathbb{R}^{3}$$
$$C_Y = [cy_1,cy_2,cy_3] \in \mathbb{R}^{3}$$
$$VPL_Y = [vply_1,vply_2,vply_3] \in \mathbb{R}^{3}$$
Seja $DZ$ o vetor de decisão de investimento no controle de tráfego e, Downsberg , $CZ$ seu vetor de custos e $VPLZ$ seu vetor de VPL. Então, 
$$D_Z = [dz_1,dz_2,dz_3] \in \{0,1\}^{3} \subset \mathbb{R}^{3}$$
$$C_Z = [cz_1,cz_2,cz_3] \in \mathbb{R}^{3}$$
$$VPL_Z = [vplz_1,vplz_2,vplz_3] \in \mathbb{R}^{3}$$

Desse modo, nosso objetivo é maximizar o VPL combinado dos projetos, tendo em vista a restrição de custo total.

Desse modo, definimos o produto escalar tal que sejam $X,Y$ vetores, $X = [x_1,x_2,...,x_k]$ e $y = [y_1,y_2,...,y_k]$
Então,
$$ X \cdot Y = (x_1y_1+x_2y_2 \;+\; ... +\; x_ky_k) \in \mathbb{R} $$ 

Agora, vamos definir as seguintes funções.
$$L_X: \mathbb{R} \rightarrow \mathbb{R}, \; L_X(VPL_X,D_X) = VPL_X \cdot D_X $$
$$L_Y: \mathbb{R} \rightarrow \mathbb{R}, \; L_Y(VPL_Y,D_Y) = VPL_Y \cdot D_Y $$
$$L_Z: \mathbb{R} \rightarrow \mathbb{R}, \; L_Z(VPL_Z,D_Z) = VPL_Z \cdot D_Z $$

Portanto, nosso objetivo é
$$\max \limits_{d_x \in D_X,d_y \in D_Y,d_z \in D_Z} \;[L_X + L_Y + L_Z], \; s.a. (D_X \cdot C_X + D_Y \cdot C_Y + D_Z \cdot C_Z) \leq 5000,\; \exists! \;1 \in D_X,D_Y,D_Z$$
  
#### Resultados
$$VPL^{*} = USD\; 6,0 \;milhões$$
Ou seja, o conjunto ideal de projetos é o *Asfalto duas faixas* para a avenida entre Augen e Burger, *reparar existente* em relação à ponte na Cay Road e, por fim, o *mergulhão* para o controle de tráfego em Downsberg.  

  
### Parte II  
Para resolver o problema tendo em vista à relação de dependência entre os projetos 2 e 4 com os projetos 6 e 7, criaremos 4 variáveis artificais que serão os projetos combinados.  
$$((Projeto\;2) \rightarrow (Projeto\;6 \;\vee\;Projeto7)\; \wedge\; (Projeto\;4) \rightarrow (Projeto\;6 \vee Projeto\;7))$$
Note que a recíproca não vale para ambos os casos. Os Projetos 6 e 7 podem ocorrer sem que os projetos 2 e 4 ocorram também.  

Logo, resolveremos o problema excluindo o conjunto $\{Projeto_2,Projeto_4\}$ **individualmente**, e adicionando os seguintes projetos **virtuais**:
$$Projetos = \{Projeto2_6,Projeto2_7,Projeto4_6,Projeto4_7\}$$
Nosso objetivo, desse modo, é
$$\max \limits_{d_x \in D_X,d_y \in D_Y,d_z \in D_Z} \;[L_X + L_Y + L_Z], \; s.a. (D_X \cdot C_X + D_Y \cdot C_Y + D_Z \cdot C_Z) \leq 5000,\; (1 \in D_X,D_Y) \leftrightarrow (1 \notin D_{X/Y}),\; \exists!\;1 \in D_Z$$
  
#### Resultados  
Por fim,
$$VPL^{*} = USD\; 7,8 \;milhões$$
Sendo as opções condicionadas de *asfalto, 4 faixas* e *adicionar faixa* à ponte, e *mergulhão* no controle de tráfego de Downsberg, as opções ótimas.

  
  
## Questão 3
  
### Parte I  
Agora nosso objetivo é otimizar o VPL acumulado dos projetos, tendo em vista a restrição anual de orçamento.  

Sejam os seguintes vetores:  

O vetor de decisão
$$D = [d_1,d_2,d_3,d_4,d_5,d_6,d_7]$$
  
O vetor de fluxos do ano 1
$$F_1 = [90,80,50,20,40,80,80]$$
  
O vetor de fluxos do ano 2
$$F_2 = [58,80,100,64,50,20,100]$$
  
E o vetor do VPL 
$$VPL = [150,200,100,100,120,150,240]$$
  
Desse modo, desejamos
$$\max\;VPL \cdot D, \; s.a. F_1 \cdot D \leq Orçamento_1, \; F_2 \cdot D \leq Orçamento_2 $$
  
Sendo $Orçamento_i$ igual ao orçamento dedicado àquele ano, **mais** o acumulado à taxa de $10\%$ do ano $i-1$ .
  
##### Resultados  
Nosso vetor de decisão ficou tal que
$$D =[1,0,0,1,1,0,1]$$
  
Ou seja, diante das restrições, foi decido o investimento no Projeto 1, no Projeto 4, no Projeto 5 e no Projeto 7.  

$$VPL^{*} =  610$$
  
### Parte II  
Ao variar o valor do **orçamento anual**, notamos que os resultados ficam estáveis no intervalo
$$OrçamentoAnual \;=\; [250,255]$$
