---
title: "Módulo II: Decisão Sob Incerteza"
author: "Marcos Cavalcanti (1920533) & Gustavo Deutscher (1820438)"
date: "31/03/2022"
output: word_document
---

## Questão 1

### Item 1.1
Segue abaixo o **Diagrama de Influência** e a **Árvore de Decisão** equivalente.  


É possível notar que a estratégia ótima para o investidor neutro a risco é optar pelo Título Y.  

### Item 1.2

De acordo com a definição, faremos $U = E$ e diremos que esta é a representação neutra a risco. Dessa forma, seja $\boldsymbol{\chi} = \{X_1,X_2,...,X_k\}$ um conjunto que abriga diferentes ações que um indivíduo tem disponível. Então, 
$$U(X) = E[X],\; \forall X \in \chi$$
E, para encontrar a decisão ótima feita pelo investidor,
$$X^{*} = \arg \max\limits_{X \in \boldsymbol{\chi}}\; E[X]$$
Dessa maneira, voltemos ao problema da questão. Podemos definir no conjunto de possibilidades da seguinte maneira: $\chi = \{X,Y\} $ , tal que $X$ é a decisão de investir no Título X e $Y$ a decisão de investir no Título Y. Temos, pois,
$$U(X) = E(X) = - \$ 21$$

$$U(Y) = E(Y) = 3$$
Logo, como $U(Y) > U(X)$, o investido prefere investir no Título Y ao invés de investir no Título X.
$$Y \succ X$$

### Item 1.3
Segue abaixo o **Perfil de Risco** e o **Perfil de Risco Acumulado** da decisão ótima identificada no item Q1.2.  


### Item 1.4
Assumindo um investidor Neutro a Risco, é necessário que $E(Z) = U[Z] > U[Y] = E(Y)$.
$$E[Z] = E[X] + E[z] > E[Y]$$
Logo,
$$-12,5 + z > 3$$
E, portanto,
$$z > 15,5$$

### Item 1.5
Considerando ainda um cenário em que o investidor é neutro a risco, agora estamos em uma situação limite, isto é, o valor de $z$ que torne o investimento em $Z$ indiferente de $Y$, ou ainda, $U(Z) = U(Y)$.
$$E[Z] = E[X] + E[z] = E[Y]$$
$$-12,5 + z = 3$$
$$z = 15,5$$

## Questão 2

### Item 2.1
Segue abaixo o **Diagrama de Influência** e a **Árvore de Decisão** equivalente.




Uma vez que temos um investidor neutro a risco, o que vale é o valor esperado das suas decisões. Portanto,
$$(E(B) > E(A)) \rightarrow (B \succ A)$$

### Item 2.2
Uma vez que temos um investidor neutro a risco, o que é determinante é o valor esperado das suas decisões. Temos que $E(A) = 4,5$ e $E(B) = 4,8$. Logo,
$$U(A) = E(A) = 4,5$$
$$U(B) = E(B) = 4,8$$
Portanto,
$$(U(B) > U(A)) \rightarrow (B \succ A)$$
Isto é, optamos pela Loteria B.  


### Item 2.3
Segue abaixo o **Perfil de Risco** e o **Perfil de Risco Acumulado** da decisão ótima identificada no item Q2.2.





### Item 2.4

$$\min\limits_{p_1,p_2,p_3} p_1 ,\; s.a.\; 0\leq p_1,p_2,p_3\leq 1, \;p_1+p_2+p_3 = 1,\;E(B) = 4,8,\;E(A) \geq E(B)$$
$$p_1^{*} = 32,53\%$$

## Questão 3
Após gerar a árvore de decisão, vamos resolvê-la a fim de encontrar as decisões ótimas do gestor da Pennzoil!  
  
  


Reduzindo o nó de incerteza "Decisão da Suprema Corte" a um nó final, temos que este vale: 3,31  

Reduzindo o nó de incerteza "Pennzoil aceita contra oferta?" a um nó final, temos este valendo: 3,50.  

Assim, temos a árvore reduzida abaixo:   




## Questão 4

### Item 4.1
Segue abaixo o **Diagrama de Influência** e a **Árvore de Decisão** equivalente.



### Item 4.2
Seja A $\equiv$ **com investimento inicial**, B $\equiv$ **sem investimento inicial**.  
Investimento Inicial = 150  
P(Fase I) = 0,7  
P(Fase II, com investimento) = 0,7  
P(Fase II, sem investimento) = 0,4  
P(Fase III) = 0,5  
P(Fase IV) = 0,9  
Retorno = 1200  

$$E(A) = - Investimento Incial \;+\; [P(Fase I)*P(Fase II, com Investimento)*P(Fase III)*P(Fase IV)]* Retorno$$
$$E(B) = [P(Fase I)*P(Fase II, sem Investimento)*P(Fase III)*P(Fase IV)]* Retorno$$
Logo,
$$E(A) = \$114.600$$
$$E(B) = \$151.200$$


### Item 4.3
Segue abaixo o **Perfil de Risco** da decisão de investimento e não-investimento.  


### Item 4.4
Queremos achar a probabilidade tal que
$$-150 + [0,70*(0,40+p)*0,50*0,90]*1200 \;=\; (0,70*0,40*0,50*0,90)*1200$$
Logo, 
$$p = 39,68 \%$$  
  
### Item 4.5
Por fim,
$$E(Com Investimento) = 0,70*(-150+0,7968*0,50*0,90*1200*10^{3}) = 301.085$$
$$E(Sem Investimento) = 0,70*0,40*0,50*0,90*1200*10^{3}) = 151.200$$
Portanto,
$$E(Flexibilidade) = E(Com Investimento) - E(Sem Investimento) = 149.885$$

  
## Questão 5

### Item 5.1
O exercício em questão tem por objetivo maximizar o valor esperado das decisões de Lassiter.  
Seja $$X = [5.000,7.500,10.000]$$ um vetor das opção de Lassiter. Então, nosso objetivo é
$$\max \limits_{x \in X} \ E(X)$$  
  
### Item 5.2
Como observado pela árvore de decisão, Lassiter deve pedir **7.500** camisetas.



