create table oxford_measures(
CountryName varchar NULL,                       
CountryCode varchar NULL,                      
RegionName varchar NULL,                        
RegionCode varchar NULL,
CityName varchar NULL,
CityCode varchar NULL,                        
Jurisdiction varchar NULL,                     
Date date NULL,                            
C1_School closing numeric NULL,                
C1_Flag numeric NULL,
C1_Notes varchar NULL,                         
C2_Workplace_closing numeric NULL,              
C2_Flag numeric NULL, 
C2_Notes varchar NULL,                           
C3_Cancel numeric NULL,                          
C3_Flag numeric NULL,
C3_Notes varchar NULL,                           
C4_Restrictions_on_gatherings numeric NULL,      
C4_Flag numeric NULL,
C4_Notes varchar NULL,                           
C5_Close_public_transport numeric NULL,         
C5_Flag numeric NULL,
C5_Notes varchar NULL,                            
C6_Stay_at_home_requirements numeric NULL,      
C6_Flag numeric NULL,
C6_Notes varchar NULL, 
C7_Restrictions_on_internal_movement numeric NULL,
C7_Flag numeric NULL,
C7_Notes varchar NULL,
C8_International_travel_controls numeric NULL,
C8_Notes varchar NULL
E1_Income_support numeric NULL,
E1_Flag numeric NULL,
E1_Notes varchar NULL, 
E2_Debt_contract_relief numeric NULL,
E2_Notes varchar NULL,
E3_Fiscal_measures numeric NULL,
E3_Notes varchar NULL, 
E4_International_support numeric NULL,
E4_Notes varchar NULL, 
H1_Public_information_campaigns numeric NULL, 
H1_Flag numeric NULL,
H1_Notes varchar NULL,
H2_Testing_policy numeric NULL,
H2_Notes varchar NULL,
H3_Contact_tracing numeric NULL,
H3_Notes varchar NULL, 
H4_Emergency_investment_in_healthcare numeric NULL,
H4_Notes varchar NULL,
H5_Investment_in_vaccines numeric NULL,
H5_Notes varchar NULL, 
H6_Facial_Coverings numeric NULL, 
H6_Flag numeric NULL,
H6_Notes varchar NULL, 
H7_Vaccination_policy numeric NULL,
H7_Flag numeric NULL, 
H7_Notes varchar NULL,
H8_Protection_of_elderly_people numeric NULL,
H8_Flag numeric NULL,
H8_Notes varchar NULL,
M1_Wildcard numeric NULL,
M1_Notes varchar NULL,
V1_Vaccine_Prioritisation varchar NULL,
V1_Notes varchar NULL,
V2_Vaccine_Availability varchar NULL,
V2_Notes varchar NULL,
V3_Vaccine_Financial _Support varchar NULL,
V3_Notes varchar NULL,
V4_Mandatory_Vaccination varchar NULL,
V4_Notes varchar NULL,
ConfirmedCases int NULL,
ConfirmedDeaths int NULL,
StringencyIndex numeric NULL,
StringencyIndexForDisplay numeric NULL,
StringencyLegacyIndex numeric NULL,
StringencyLegacyIndexForDisplay numeric NULL,
GovernmentResponseIndex numeric NULL,
GovernmentResponseIndexForDisplay numeric NULL, 
ContainmentHealthIndex numeric NULL,
ContainmentHealthIndexForDisplay numeric NULL,
EconomicSupportIndex numeric NULL,
EconomicSupportIndexForDisplay numeric NULL
);


copy oxford_measures
from 'D:\Databases\Oxford_Measures\Oxford_Measures.csv'
with delimiter ','
csv header
;

